vector_tokens:
 #g++ test_vector_tokens.cpp tabla_token.cpp pre_processing.cpp normalizador.cpp automaton.cpp
 g++ test_vector_tokens.cpp tabla_token.cpp pre_processing.cpp normalizador.cpp automaton.cpp -std=c++0x
