
test_compilador_processing:
	g++ -o compilador -std=c++11  test_compilador_processing.cpp  lector_tabla_anagra/gramatica_expan.cpp lector_tabla_anagra/tabla_slr.cpp  analizador_lexico/tabla_token.cpp analizador_lexico/automata.cpp analizador_lexico/analizador_lexico.cpp
