

#tabla_test: test_tabla_token.o  tabla_token.o  automaton/home/luigy/Desktop/compiladores/compilador/automatas/automaton/automaton.o
#g++  test_tabla_token.o  tabla_token.o  /home/luigy/Desktop/compiladores/compilador/automatas/automaton/automaton.o
tabla_test:
	g++ test_tabla_token.cpp tabla_token.cpp  /home/luigy/Desktop/compiladores/compilador/automatas/automaton/automaton.cpp



#test_tabla_token: test_tabla_token.cpp
#tabla_token: tabla_token.cpp tabla_token.hpp
#/home/luigy/Desktop/compiladores/compilador/automatas/automaton/automaton: /home/luigy/Desktop/compiladores/compilador/automatas/automaton/automaton.cpp /home/luigy/Desktop/compiladores/compilador/automatas/automaton/automaton.hpp
